-- Все уровни иерархий

SELECT [CATALOG_NAME] as [DATABASE],
    CUBE_NAME AS [CUBE],
    [DIMENSION_UNIQUE_NAME] AS [DIMENSION],
    [HIERARCHY_UNIQUE_NAME] AS [HIERARCHY],
    LEVEL_CAPTION AS [LEVEL],
    [LEVEL_NAME],
    [LEVEL_NUMBER] AS [LEVEL NUMBER],
    [LEVEL_NAME_SQL_COLUMN_NAME] AS [NAME_COLUMN],
    [LEVEL_UNIQUE_NAME_SQL_COLUMN_NAME] AS [UNIQUE_NAME_COLUMN],
    [LEVEL_KEY_SQL_COLUMN_NAME] AS [KEY_COLUMN]
 FROM $system.MDSchema_levels
 WHERE CUBE_NAME  = '<Имя куба>' -- Измените отбор здесь
 AND LEVEL_ORIGIN=3
 order by [DIMENSION_UNIQUE_NAME]