-- Все меры

SELECT 
    [CATALOG_NAME] as [DATABASE],
    CUBE_NAME AS [CUBE],
    [MEASUREGROUP_NAME] AS [FOLDER],
    [MEASURE_CAPTION] AS [MEASURE],
    [MEASURE_IS_VISIBLE]
FROM $SYSTEM.MDSCHEMA_MEASURES
 WHERE CUBE_NAME  = '<Имя куба>' -- Измените отбор здесь
 ORDER BY [MEASUREGROUP_NAME]